// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "检查后端 API 服务是否运行正常",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "服务健康检查",
                "responses": {
                    "200": {
                        "description": "服务运行正常",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "service": {
                                                    "type": "string"
                                                },
                                                "version": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ipfs/upload": {
            "post": {
                "description": "统一 IPFS 上传入口。默认执行普通上传；当 query 参数 scene=proof 时，会先进行存证重复校验再上传。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储"
                ],
                "summary": "上传文件到 IPFS",
                "parameters": [
                    {
                        "type": "file",
                        "description": "待上传文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "可选 metadata JSON 字符串",
                        "name": "metadata",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "上传场景，proof 表示启用重复校验",
                        "name": "scene",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件上传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.UploadResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "内部服务配置错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "502": {
                        "description": "上游服务错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/proofs": {
            "get": {
                "description": "根据钱包地址、分页获取存证记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存证"
                ],
                "summary": "获取存证列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "钱包地址",
                        "name": "wallet_address",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取存证列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "items": {
                                                    "type": "array",
                                                    "items": {
                                                        "$ref": "#/definitions/models.Proof"
                                                    }
                                                },
                                                "pagination": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/proofs/{file_hash}": {
            "get": {
                "description": "根据文件哈希获取存证详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存证"
                ],
                "summary": "获取存证详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件哈希",
                        "name": "file_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取存证详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Proof"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "未找到该存证",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "获取全站存证数据统计（如存证总数、数据库状态等）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取存证统计",
                "responses": {
                    "200": {
                        "description": "成功获取统计信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.ProofStats"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Proof": {
            "type": "object",
            "properties": {
                "block_number": {
                    "type": "integer"
                },
                "chain_id": {
                    "type": "string"
                },
                "cid": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "contract_address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "file_hash": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "proof_created_at": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "models.ProofStats": {
            "type": "object",
            "properties": {
                "database_enabled": {
                    "type": "boolean"
                },
                "latest_proof_at": {
                    "type": "string"
                },
                "total_proofs": {
                    "type": "integer"
                },
                "total_storage": {
                    "type": "integer"
                },
                "total_users": {
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码 (如 200, 4001, 5002 等)",
                    "type": "integer"
                },
                "data": {
                    "description": "成功的业务数据"
                },
                "error": {
                    "description": "详细的错误调试信息 (可选)",
                    "type": "string"
                },
                "message": {
                    "description": "给前端显示的提示信息",
                    "type": "string"
                }
            }
        },
        "service.UploadResult": {
            "type": "object",
            "properties": {
                "cid": {
                    "description": "IPFS 唯一内容标识符 (Hash)",
                    "type": "string"
                },
                "file_hash": {
                    "description": "后端计算的文件 SHA256 哈希",
                    "type": "string"
                },
                "file_name": {
                    "description": "原始文件名",
                    "type": "string"
                },
                "file_size": {
                    "description": "文件大小 (字节)",
                    "type": "integer"
                },
                "gateway_url": {
                    "description": "可直接访问文件的网关 URL",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ChainVerify API",
	Description:      "ChainVerify 存证平台后端 API 文档。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
